### ISSUE TITLE
some instructions on install for Mac/OSX would be good

### ISSUE THREAD

**Issue by SogoGolf** [telerik/blazor-docs#6]

**Comment by marin-bratanov** [comment]
Hi,

Using the NuGet feed should be applicable for MacOS too: [https://docs.telerik.com/blazor-ui/installation/nuget](https://docs.telerik.com/blazor-ui/installation/nuget). You should be able to use nuget.exe through Mono or your package manager. Make sure to store the credentials in plain text if you don't get results immediately, because the .NET Core tooling still has some hiccups with encrypted credentials.

If this does not work out, you can use the zip archive and a local feed: [https://docs.telerik.com/blazor-ui/installation/zip](https://docs.telerik.com/blazor-ui/installation/zip).

The instructions on creating a project use Visual Studio for Window,s but the interface should be similar enough under Mac as well.

If this does not suffice, what are the more specific instructions you would want to see for Mac? The UI for Blazor installation boils down to having the nuget package in the project for the most part, and it is no different than any other nuget package.

Regards,
Marin

**Comment by SogoGolf** [comment]
Thanks Marin. I’ll take a look at this and revert

 

Regards,

Angus Johnston

Lead Developer

SOGO Golf

Mob: +61 400 44 29 23

**Comment by marin-bratanov** [comment]
Sure, give things a try and let me know if you have difficulties. You can always also [open a support ticket](https://www.telerik.com/account/support-tickets?pid=1952) for assistance.

**Comment by marin-bratanov** [comment]
I haven't heard about issues in a week or so, and I will close this item as resolved with the available information. If anything pops up, you can always comment here, open a new issue or a ticket, and I'll be happy to assist.
