### ISSUE TITLE
Blazor icons are broken

### ISSUE THREAD

**Issue by MrZander** [telerik/blazor-docs#702]
>List of icon names to use in Telerik components Icon parameters

>The Icon list failed to load. You can see the available icons in the Kendo UI Font Icons article. To use them with UI for Blazor, remove the k-i- prefix. If you are seeing this, open an issue to let us know the icon list is broken.

**Comment by marin-bratanov** [comment]
Thank you for bringing this up @MrZander . I just tested the page and it seems to load well for me on Chrome, Edge, Firefox, Vivaldi. Could you try in Incognito mode, or with a different browser? If that or clearing the browser cache does not help, can you check the browser console for errors? Perhaps the request to the themes repo that downloads the list of icons fails on your machine due to network restrictions, you can also check for that.
Looking forward to your feedback.

**Comment by marin-bratanov** [comment]
I will take it that things are working now and I will close this. If the issue manifests, let me know.

**Comment by MrZander** [comment]
Yes it is working now

**Comment by aubhik-mazumdar** [comment]
Has this been verified by everybody? I still have issues sometimes
